MONGO_MESSAGECENTER_IP = "10.8.1.10"
MONGO_MESSAGECENTER_PORT = "27017"
MONGO_MESSAGECENTER_USERNAME = "root"
MONGO_MESSAGECENTER_PASSWORD = "gold123456"
MONGO_MESSAGECENTER_DB_NAME = "messageCenter"
MONGO_MESSAGECENTER_TABLE_LARGESCREENENTITY = "LargeScreenEntity"
MONGO_MESSAGECENTER_CONNECT = "mongodb://"+ MONGO_MESSAGECENTER_USERNAME + ":" + MONGO_MESSAGECENTER_PASSWORD+"@"+MONGO_MESSAGECENTER_IP+":"+MONGO_MESSAGECENTER_PORT+"/"+MONGO_MESSAGECENTER_DB_NAME
